import type { Metadata } from "next";
import { Geist, Geist_Mono, Michroma } from "next/font/google";
import '@/app/ui/global.css';
import Header from "@/app/ui/header";


const michroma = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${michroma.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Header/>
        {children}
      </body>
    </html>
  );
}
