import type { Metadata } from "next";
import { Geist, Geist_Mono, Michroma } from "next/font/google";
import '@/app/ui/global.css';
import Header from "@/app/ui/header";

// Configure Michroma font for the application
const michroma = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: "400",
});

// Page metadata for SEO and browser display
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component - wraps all pages with common structure
// Includes global fonts, CSS, and the header component
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${michroma.variable} h-screen antialiased`}
    >
      <body className="min-h-screen flex flex-col font-sans">
        <Header/>
        {children}
      </body>
    </html>
  );
}
